services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_lms
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_management_system_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresql:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - spring-lms

  rabbitmq:
    image: rabbitmq:4.0.5-management-alpine
    container_name: rabbitmq_lms
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring-lms

networks:
  spring-lms:
    driver: bridge
volumes:
  postgresql:
    driver: local