services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_lms
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresql:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - spring-lms

  cache:
    image: redis:7.2.7-alpine
    container_name: redis_lms
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - spring-lms
    command: [ "redis-server" ]

  rabbitmq:
    image: rabbitmq:4.0.5-management-alpine
    container_name: rabbitmq_lms
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring-lms
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.1
    container_name: keycloak_lms
    ports:
      - "9090:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    networks:
      - spring-lms
    command:
      - "start-dev"

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      - spring-lms
    healthcheck:
      test: ["CMD", "wget", "-q", "--tries=1", "--spider", "http://localhost:9411/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  spring-lms:
    driver: bridge
volumes:
  postgresql:
    driver: local