spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_management_system_db
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8088

