spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_management_system_db
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/library-realm"

server:
  port: 8088

rabbitmq:
  exchange:
    name: "email_exchange"
  queue:
    name: "queue_name"
  routing-key: "email_routing_key"

application:
  allowed:
    origins: "http://localhost:3000"