spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 20MB
  profiles:
    active: dev

springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1/
